trigger:
  branches:
    include:
    - master
    - 'v*'
    - 'validate/*'
  paths:
    exclude:
    - doc/
    - '*.md'
    - .vscode/
    - .github/

parameters:
- name: includeMacOS
  displayName: Build on macOS
  type: boolean
  default: false # macOS is often bogged down in Azure Pipelines

variables:
  TreatWarningsAsErrors: true
  UpdateXlfOnBuild: false # force build breaks if xlf files aren't updated on dev box with resx changes
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  BuildConfiguration: Release
  BuildPlatform: Any CPU
  codecov_token: 9a7c2ba3-0a4b-4479-96e8-3bfd01a982f6
  NUGET_PACKAGES: $(Agent.TempDirectory)/.nuget/packages

jobs:
- template: azure-pipelines/build.yml
  parameters:
    includeMacOS: ${{ parameters.includeMacOS }}
    ShouldSkipOptimize:
- template: azure-pipelines/richnav.yml
