parameters:
- name: SignType
- name: ShouldSkipOptimize

steps:

- task: ms-vseng.MicroBuildTasks.965C8DC6-1483-45C9-B384-5AC75DA1F1A4.MicroBuildOptProfPlugin@4
  inputs:
    optimizationInputsDropNamePrefix: OptimizationInputs/DevDiv/vs-streamjsonrpc
    getDropNameByDrop: true
    ShouldSkipOptimize: ${{ parameters.ShouldSkipOptimize }}
  displayName: Install OptProf Plugin

- task: MicroBuildSigningPlugin@2
  inputs:
    signType: ${{ parameters.SignType }}
    zipSources: false
  displayName: Install MicroBuild Signing Plugin
  condition: and(succeeded(), ne(variables['Hosted'], 'true'))
