parameters:
- name: ShouldSkipOptimize

steps:
- task: MicroBuildOptProfPlugin@5
  inputs:
    ProfilingInputsDropName: ProfilingInputs/$(System.TeamProject)/$(Build.Repository.Name)/$(Build.SourceBranchName)/$(Build.BuildNumber)
    OptimizationInputsLookupMethod: DropPrefix
    DropNamePrefix: OptimizationInputs/$(System.TeamProject)/$(Build.Repository.Name)
    ShouldSkipOptimize: ${{ parameters.ShouldSkipOptimize }}
  displayName: Install OptProf Plugin

- task: MicroBuildSigningPlugin@2
  inputs:
    signType: $(SignType)
    zipSources: false
  displayName: Install MicroBuild Signing Plugin
