trigger:
  branches:
    include: ["master", "v*", "*_validate"]
  paths:
    exclude: ["doc", "*.md"]

variables:
  TreatWarningsAsErrors: true
  UpdateXlfOnBuild: false # force build breaks if xlf files aren't updated on dev box with resx changes
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  BuildConfiguration: Release
  BuildPlatform: Any CPU

jobs:
- job: Windows
  pool: VSEng-MicroBuildVS2017
  steps:
  - template: build.yml
