jobs:
- job: RichCodeNavUpload
  displayName: Rich Code Navigation Upload to Production
  pool: Hosted Windows 2019 with VS2019
  steps:
  - template: install-dependencies.yml
  - task: RichCodeNavIndexer@0
    displayName: RichCodeNav Upload
    inputs:
      languages: 'csharp'
      environment: production
      githubServiceConnection: Microsoft
      isPrivateFeed: false
    continueOnError: true
