trigger: none # We only want to trigger manually or based on resources

resources:
  pipelines:
  - pipeline: CI
    source: vs-StreamJsonRpc
    tags:
    - Real signed
    trigger:
      tags:
      - Real signed
      - auto-insertion

stages:
- stage: VS
  displayName: VS insertion
  jobs:
  - deployment: insertion
    pool: VSEng-RMPool
    environment: No-Approval
    strategy:
      runOnce:
        deploy:
          steps:
          - template: release-deployment-prep.yml
          - download: CI
            artifact: VSInsertion-Windows
            displayName: Download VSInsertion-Windows artifact
          - task: NuGetCommand@2
            displayName: Push CoreXT packages to VS feed
            inputs:
              command: push
              packagesToPush: $(Pipeline.Workspace)/CI/VSInsertion-windows/*.nupkg
              publishVstsFeed: 97a41293-2972-4f48-8c0e-05493ae82010
              allowPackageConflicts: true
          - task: MicroBuildInsertVsPayload@3
            displayName: Insert VS Payload
            inputs:
              TeamName: $(TeamName)
              TeamEmail: $(TeamEmail)
              InsertionPayloadName: $(Build.Repository.Name) $(Build.BuildNumber)
              InsertionBuildPolicy: Request Perf DDRITs
              AutoCompletePR: true
              AutoCompleteMergeStrategy: Squash
          - task: MicroBuildCleanup@1
            displayName: Send Telemetry
